//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicLoad
    {
        public decimal ID { get; set; }
        public Nullable<decimal> DisciplinID { get; set; }
        public Nullable<decimal> GroupID { get; set; }
        public Nullable<decimal> TeacherID { get; set; }
        public Nullable<decimal> AcademicYearID { get; set; }
        public Nullable<decimal> Semester { get; set; }
    }
}
