//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public decimal ID { get; set; }
        public decimal PeopleID { get; set; }
        public decimal GroupID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual People People { get; set; }
    }
}
